# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - akabot_arm_controller
    - hand_controller

  akabot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - top_plate_joint
      - lower_arm_joint
      - upper_arm_joint
      - wrist_joint
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - claw_base_joint
      - right_claw_joint
      - left_claw_joint
    action_ns: gripper_cmd
    default: true